Section "Device"
    Identifier      "Default fbdev Device"
    Driver          "armada"

    # Support hotplugging displays?
    Option          "Hotplug"       "FALSE"

    # Support hardware cursor if available?
    Option          "HWCursor"      "TRUE"

    # Use GPU acceleration?
    Option          "UseGPU"        "TRUE"

    # Provide Xv interfaces?
    Option          "XvAccel"       "TRUE"

    # Prefer overlay for Xv (TRUE for armada-drm, FALSE for imx-drm)
    Option          "XvPreferOverlay" "FALSE"

    # Support DRI interfaces
    Option          "DRI"           "TRUE"
    Option          "DRI3"          "TRUE"
EndSection
